# ---- Base Node ----
FROM node:21-alpine AS base
WORKDIR /app
COPY package*.json ./

# ---- Dependencies and Checks ----
FROM base AS dependencies  
RUN npm install --legacy-peer-deps

# ---- Copy Files/Build ----
FROM dependencies AS build  
WORKDIR /app
COPY . /app
RUN npm run build-production

# --- Release with Nginx ----
FROM nginx:1-alpine AS release  
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/conf.d/  /etc/nginx/conf.d/
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
