FROM node:16.4.2-alpine
WORKDIR /backend
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV TZ=Asia/Kolkata
# COPY package.json ./
# COPY package-lock.json ./
COPY ./ /backend
RUN apk add --no-cache tzdata \
    && npm i
CMD ["npm", "run", "start"]