FROM ubuntu:20.04 AS build
RUN apt-get update && apt-get install -y tzdata
ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY so_files/ /usr/lib/x86_64-linux-gnu/
WORKDIR /Aksha_Anomaly_Model_Trainer
COPY main ./
ENTRYPOINT ["./main"]
