FROM ubuntu:latest  
WORKDIR /opt/aksha
RUN apt-get update && DEBIAN_FRONTEND=noninteractive && apt-get install --no-install-recommends --assume-yes && apt-get install nodejs -y && apt-get install npm -y && apt-get install nginx -y
#Copy App Source inside docker image
COPY frontend /opt/aksha
COPY backend /opt/backend
COPY script /opt/script
RUN npm i && npm run build-production && cp -r build/* /var/www/html/
RUN npm install pm2 -g 
COPY frontend/nginx/default  /etc/nginx/sites-enabled/
RUN cd /opt/backend && npm i
EXPOSE 3000
EXPOSE 5000
CMD ["/usr/bin/python3", "/opt/script/start_aksha.py"]
